Fix grep check

diff --git a/.github/workflows/validate-file-extensions.yaml b/.github/workflows/validate-file-extensions.yaml
--- a/.github/workflows/validate-file-extensions.yaml
+++ b/.github/workflows/validate-file-extensions.yaml
@@ -28,5 +28,7 @@ jobs:
           echo "$ADDED_OR_MODIFIED_FILES"
 
           # Check if any .yml files are present
-          printf "%s\n" "$ADDED_OR_MODIFIED_FILES" | grep -qiE '\.yml$' && \
-          { echo "::error .yml files detected! Please change .yml to .yaml files."; exit 1; }
+          if printf "%s\n" "$ADDED_OR_MODIFIED_FILES" | grep -qiE '\.yml$'; then
+            echo "::error .yml files detected! Please change .yml to .yaml files."
+            exit 1
+          fi
